/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as RutaRouteImport } from './routes/ruta'
import { Route as ReporteRouteImport } from './routes/reporte'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'

const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const RutaRoute = RutaRouteImport.update({
  id: '/ruta',
  path: '/ruta',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporteRoute = ReporteRouteImport.update({
  id: '/reporte',
  path: '/reporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/productos': typeof ProductosRoute
  '/reporte': typeof ReporteRoute
  '/ruta': typeof RutaRoute
  '/rutas': typeof RutasRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/productos': typeof ProductosRoute
  '/reporte': typeof ReporteRoute
  '/ruta': typeof RutaRoute
  '/rutas': typeof RutasRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/productos': typeof ProductosRoute
  '/reporte': typeof ReporteRoute
  '/ruta': typeof RutaRoute
  '/rutas': typeof RutasRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/clientes'
    | '/configuracion'
    | '/historial'
    | '/productos'
    | '/reporte'
    | '/ruta'
    | '/rutas'
    | '/clientes/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/clientes'
    | '/configuracion'
    | '/historial'
    | '/productos'
    | '/reporte'
    | '/ruta'
    | '/rutas'
    | '/clientes/$clientId'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/clientes'
    | '/configuracion'
    | '/historial'
    | '/productos'
    | '/reporte'
    | '/ruta'
    | '/rutas'
    | '/clientes/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracionRoute: typeof ConfiguracionRoute
  HistorialRoute: typeof HistorialRoute
  ProductosRoute: typeof ProductosRoute
  ReporteRoute: typeof ReporteRoute
  RutaRoute: typeof RutaRoute
  RutasRoute: typeof RutasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruta': {
      id: '/ruta'
      path: '/ruta'
      fullPath: '/ruta'
      preLoaderRoute: typeof RutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporte': {
      id: '/reporte'
      path: '/reporte'
      fullPath: '/reporte'
      preLoaderRoute: typeof ReporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClientIdRoute: typeof ClientesClientIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClientIdRoute: ClientesClientIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracionRoute: ConfiguracionRoute,
  HistorialRoute: HistorialRoute,
  ProductosRoute: ProductosRoute,
  ReporteRoute: ReporteRoute,
  RutaRoute: RutaRoute,
  RutasRoute: RutasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
